### ISSUE TITLE
Unexpected button (keypress) behaviour (change pulse instead of current state)

### ISSUE THREAD

**Issue by nhjschulz** [BlueAndi/ZumoHALWebots#7]
The button pressed / released API's only provide a single true result when the button state change is seen.  It behaves like an level switch interrupt.  This causes trouble with apps that do their own debounce by for example accepting a press only if it is seen for some time. 

The epected behaviour is to provided the "real" button state, i.e. "pressed = true" as long as it is pressed. and "released=true" as long as it is released.

Background: The interface to Webots was done this way to mimic the behaviour of the Pololu Zumo PushButton Hall lib (i.e. see Zumo32U4ButtonA::getSingleDebouncedPress()). A similar change in  [ZumoHALATmega32u4](https://github.com/BlueAndi/ZumoHALATmega32u4/tree/main) should also change the Button Press/release API's to provide the real state, not change pulses.

**Comment by BlueAndi** [comment]
Fixed in the upcoming v0.2.1
Thanks!
